return {
	{ "bash-language-server", auto_update = true },
	"shellcheck",
	"lua_ls",
	"stylua",
	{ "ts_ls", auto_update = true },
	"bashls",
	{ "gopls", auto_update = true },
	"ansiblels",
	"jsonls",
	"jsonlint",
	"yamlls",
	"ruff",
	"sqls",
	"prettier",
	"biome",
	"prettierd",
	"editorconfig-checker",
	"gofumpt",
	"golines",
	"gomodifytags",
	"gotests",
	"rust-analyzer",
	"codelldb",
}
