"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true 

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[➜](bold red) '

[package]
disabled = false

[aws]
disabled = true

[azure]
disabled = true

[gcloud]
disabled = true

[c]
disabled = false
format = 'via [$name $version] ($style)'

[dart]
format = 'via [dart $version](bold red) '

[directory]
truncation_length = 2
truncate_to_repo = true
truncation_symbol = '.../'

[git_branch]
format = 'on [$symbol$branch]($style) '
symbol = ' '
truncation_length = 256 
truncation_symbol = ''
ignore_branches = []

[git_commit]
commit_hash_length = 4
tag_symbol = '🔖 '

[golang]
format = 'via [$symbol($version )($mod_version )]($style)'

[nodejs]
format = 'via [nodejs $version](bold green) '

[hostname]
ssh_only = true
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.companyname.com'
disabled = false

[container]
format = '[$symbol \[$name\]]($style) '

[docker_context]
format = 'via [🐋 $context](blue bold)'


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

palette = "catppuccin_mocha"
